In [1]:
import pandas as pd
import glob

In [2]:
interproscan = pd.read_csv('/Users/khj/Desktop/Project_ongoing/DRBP/data/DRBP_result_analysis/analysis_raw_data/interproscan/Interproscan_result_250704.tsv',sep='\t',header=None)
interproscan

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,ENSP00000352785,bf8fed9e55b18f0adb4b5b7cb2404678,1059,PANTHER,PTHR24025,DESMOGLEIN FAMILY MEMBER,43,688,1.0E-176,T,05-07-2025,IPR050971,Cadherin domain-containing protein,GO:0005509(PANTHER)|GO:0005911(PANTHER)|GO:003...,-
1,ENSP00000352785,bf8fed9e55b18f0adb4b5b7cb2404678,1059,Pfam,PF01049,"Cadherin, Y-type LIR-motif",810,866,0.0081,T,05-07-2025,IPR000233,"Cadherin, Y-type LIR-motif",GO:0005509(InterPro)|GO:0007156(InterPro),-
2,ENSP00000352785,bf8fed9e55b18f0adb4b5b7cb2404678,1059,ProSiteProfiles,PS50268,Cadherins domain profile.,76,157,18.617403,T,05-07-2025,IPR002126,Cadherin-like,GO:0005509(InterPro)|GO:0007156(InterPro)|GO:0...,-
3,ENSP00000352785,bf8fed9e55b18f0adb4b5b7cb2404678,1059,SUPERFAMILY,SSF49313,Cadherin-like,75,157,9.85E-13,T,05-07-2025,IPR015919,Cadherin-like superfamily,GO:0005509(InterPro)|GO:0016020(InterPro),-
4,ENSP00000352785,bf8fed9e55b18f0adb4b5b7cb2404678,1059,ProSiteProfiles,PS50268,Cadherins domain profile.,386,497,17.345886,T,05-07-2025,IPR002126,Cadherin-like,GO:0005509(InterPro)|GO:0007156(InterPro)|GO:0...,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387980,ENSP00000219611,37766b056a6e3240090d3fd76576c001,1086,SMART,SM00547,zf_4,46,70,4.0E-5,T,05-07-2025,IPR001876,"Zinc finger, RanBP2-type",-,-
387981,ENSP00000219611,37766b056a6e3240090d3fd76576c001,1086,SMART,SM00547,zf_4,342,366,0.048,T,05-07-2025,IPR001876,"Zinc finger, RanBP2-type",-,-
387982,ENSP00000219611,37766b056a6e3240090d3fd76576c001,1086,SMART,SM00547,zf_4,5,29,2.1E-7,T,05-07-2025,IPR001876,"Zinc finger, RanBP2-type",-,-
387983,ENSP00000219611,37766b056a6e3240090d3fd76576c001,1086,SMART,SM00547,zf_4,414,438,8.8E-7,T,05-07-2025,IPR001876,"Zinc finger, RanBP2-type",-,-
387984,ENSP00000219611,37766b056a6e3240090d3fd76576c001,1086,ProSiteProfiles,PS50199,Zinc finger RanBP2 type profile.,143,172,9.133901,T,05-07-2025,IPR001876,"Zinc finger, RanBP2-type",-,-

In [6]:
# 파일 리스트 수집
dna_files = glob.glob('/Users/khj/Desktop/Project_ongoing/DRBP/data/DRBP_result_analysis/Binding_info/IPR_binding_info/DNA-binding_domain_IPR/*.tsv')  # 디렉토리 경로를 원하는 경로로 수정

# 각 파일을 읽어서 리스트에 담기
dna_df_list = [pd.read_csv(f, sep='\t') for f in dna_files]

# 하나의 DataFrame으로 합치기
dna_combined_df = pd.concat(dna_df_list, ignore_index=True)

# (선택) index 리셋
dna_combined_df.reset_index(drop=True, inplace=True)
DBP_IPR_list = list(dna_combined_df['Accession'])
len(DBP_IPR_list)

813

In [4]:
DBP_IPR_list

['IPR005104',
 'IPR008823',
 'IPR010776',
 'IPR014041',
 'IPR015189',
 'IPR015190',
 'IPR015285',
 'IPR019707',
 'IPR023120',
 'IPR025220',
 'IPR025959',
 'IPR027395',
 'IPR032622',
 'IPR036388',
 'IPR036390',
 'IPR038106',
 'IPR038722',
 'IPR038723',
 'IPR040501',
 'IPR040764',
 'IPR040855',
 'IPR041075',
 'IPR041516',
 'IPR041614',
 'IPR041687',
 'IPR041898',
 'IPR041899',
 'IPR045628',
 'IPR045830',
 'IPR046799',
 'IPR047417',
 'IPR048649',
 'IPR048931',
 'IPR048949',
 'IPR048976',
 'IPR049043',
 'IPR049274',
 'IPR049543',
 'IPR053882',
 'IPR054007',
 'IPR054105',
 'IPR054162',
 'IPR054382',
 'IPR054471',
 'IPR054472',
 'IPR055121',
 'IPR055224',
 'IPR055227',
 'IPR055245',
 'IPR056226',
 'IPR056395',
 'IPR056575',
 'IPR056589',
 'IPR056624',
 'IPR056808',
 'IPR056871',
 'IPR056875',
 'IPR056984',
 'IPR057283',
 'IPR057324',
 'IPR057429',
 'IPR057471',
 'IPR057511',
 'IPR057588',
 'IPR057748',
 'IPR057842',
 'IPR057846',
 'IPR058038',
 'IPR058056',
 'IPR009071',
 'IPR017967',
 'IPR019102',
 'IPR029215',
 'IPR036910',
 'IPR002694',
 'IPR036977',
 'IPR011598',
 'IPR015789',
 'IPR016637',
 'IPR024097',
 'IPR024098',
 'IPR024100',
 'IPR028819',
 'IPR028822',
 'IPR031066',
 'IPR032644',
 'IPR032655',
 'IPR032656',
 'IPR032657',
 'IPR032658',
 'IPR032659',
 'IPR032660',
 'IPR032661',
 'IPR032663',
 'IPR033348',
 'IPR037935',
 'IPR039092',
 'IPR040106',
 'IPR040157',
 'IPR044278',
 'IPR044549',
 'IPR044579',
 'IPR044658',
 'IPR045239',
 'IPR045895',
 'IPR045896',
 'IPR047093',
 'IPR047094',
 'IPR047206',
 'IPR047265',
 'IPR048064',
 'IPR050359',
 'IPR051358',
 'IPR052610',
 'IPR054502',
 'IPR056192',
 'IPR056193',
 'IPR056194',
 'IPR057021',
 'IPR057071',
 'IPR057072',
 'IPR057075',
 'IPR057310',
 'IPR002878',
 'IPR004150',
 'IPR004365',
 'IPR005220',
 'IPR006173',
 'IPR006531',
 'IPR008993',
 'IPR009590',
 'IPR010840',
 'IPR012340',
 'IPR013894',
 'IPR014724',
 'IPR015282',
 'IPR016071',
 'IPR016798',
 'IPR024422',
 'IPR025824',
 'IPR028045',
 'IPR032199',
 'IPR035437',
 'IPR036700',
 'IPR037026',
 'IPR040663',
 'IPR042470',
 'IPR044117',
 'IPR045461',
 'IPR048898',
 'IPR052401',
 'IPR055065',
 'IPR055446',
 'IPR056787',
 'IPR057139',
 'IPR057143',
 'IPR057144',
 'IPR057147',
 'IPR057300',
 'IPR057301',
 'IPR057912',
 'IPR000679',
 'IPR008013',
 'IPR013088',
 'IPR053116',
 'IPR004826',
 'IPR004827',
 'IPR040223',
 'IPR043321',
 'IPR043452',
 'IPR044168',
 'IPR044521',
 'IPR044759',
 'IPR045314',
 'IPR046347',
 'IPR047106',
 'IPR050946',
 'IPR051027',
 'IPR051882',
 'IPR052483',
 'IPR017967',
 'IPR019102',
 'IPR039655',
 'IPR047443',
 'IPR049523',
 'IPR000119',
 'IPR000232',
 'IPR000424',
 'IPR000635',
 'IPR000637',
 'IPR001083',
 'IPR001138',
 'IPR001238',
 'IPR001275',
 'IPR001346',
 'IPR001606',
 'IPR001647',
 'IPR001801',
 'IPR001845',
 'IPR001867',
 'IPR002059',
 'IPR002177',
 'IPR003150',
 'IPR003163',
 'IPR003166',
 'IPR003176',
 'IPR003212',
 'IPR003316',
 'IPR003512',
 'IPR003583',
 'IPR003602',
 'IPR003871',
 'IPR004186',
 'IPR004645',
 'IPR005104',
 'IPR005319',
 'IPR005376',
 'IPR005412',
 'IPR005559',
 'IPR005583',
 'IPR005902',
 'IPR006164',
 'IPR006199',
 'IPR006600',
 'IPR006754',
 'IPR006821',
 'IPR006871',
 'IPR007281',
 'IPR007492',
 'IPR007634',
 'IPR008116',
 'IPR008917',
 'IPR008967',
 'IPR009044',
 'IPR009061',
 'IPR009718',
 'IPR010093',
 'IPR010114',
 'IPR010260',
 'IPR010896',
 'IPR010982',
 'IPR010992',
 'IPR011109',
 'IPR011344',
 'IPR011396',
 'IPR011539',
 'IPR011615',
 'IPR011722',
 'IPR012339',
 'IPR012345',
 'IPR012346',
 'IPR012401',
 'IPR012909',
 'IPR013801',
 'IPR014483',
 'IPR014490',
 'IPR015094',
 'IPR015280',
 'IPR015300',
 'IPR015350',
 'IPR015367',
 'IPR015646',
 'IPR015886',
 'IPR015887',
 'IPR016177',
 'IPR016411',
 'IPR016634',
 'IPR016748',
 'IPR017362',
 'IPR017956',
 'IPR017967',
 'IPR018004',
 'IPR018078',
 'IPR018306',
 'IPR018384',
 'IPR018473',
 'IPR018586',
 'IPR018640',
 'IPR018668',
 'IPR018873',
 'IPR019476',
 'IPR019525',
 'IPR020313',
 'IPR020448',
 'IPR020604',
 'IPR020816',
 'IPR020900',
 'IPR020906',
 'IPR021009',
 'IPR021104',
 'IPR021961',
 'IPR022000',
 'IPR022595',
 'IPR022889',
 'IPR023188',
 'IPR023278',
 'IPR023772',
 'IPR023859',
 'IPR024061',
 'IPR024967',
 'IPR025166',
 'IPR025260',
 'IPR025707',
 'IPR025830',
 'IPR026052',
 'IPR026095',
 'IPR026162',
 'IPR026282',
 'IPR026577',
 'IPR027395',
 'IPR027444',
 'IPR028002',
 'IPR028088',
 'IPR028727',
 'IPR029839',
 'IPR031053',
 'IPR031760',
 'IPR032042',
 'IPR032200',
 'IPR032355',
 'IPR033246',
 'IPR033787',
 'IPR034072',
 'IPR034724',
 'IPR035209',
 'IPR035386',
 'IPR035408',
 'IPR035411',
 'IPR035616',
 'IPR035858',
 'IPR036362',
 'IPR036367',
 'IPR036368',
 'IPR036388',
 'IPR036390',
 'IPR036395',
 'IPR036407',
 'IPR036431',
 'IPR036623',
 'IPR036638',
 'IPR036657',
 'IPR036835',
 'IPR036864',
 'IPR036887',
 'IPR037000',
 'IPR037007',
 'IPR037059',
 'IPR037141',
 'IPR037540',
 'IPR038109',
 'IPR038173',
 'IPR038245',
 'IPR038488',
 'IPR038713',
 'IPR038722',
 'IPR038733',
 'IPR038859',
 'IPR039673',
 'IPR039779',
 'IPR040480',
 'IPR040905',
 'IPR041105',
 'IPR041150',
 'IPR041222',
 'IPR041241',
 'IPR041511',
 'IPR041552',
 'IPR041580',
 'IPR041936',
 'IPR042073',
 'IPR042075',
 'IPR042115',
 'IPR042153',
 'IPR042174',
 'IPR042361',
 'IPR042792',
 'IPR043111',
 'IPR043182',
 'IPR044101',
 'IPR044822',
 'IPR044895',
 'IPR044947',
 'IPR045830',
 'IPR046360',
 'IPR046367',
 'IPR046395',
 'IPR046832',
 'IPR046935',
 'IPR047091',
 'IPR047159',
 'IPR048045',
 'IPR048245',
 'IPR048523',
 'IPR048576',
 'IPR048681',
 'IPR048703',
 'IPR048708',
 'IPR048923',
 'IPR048929',
 'IPR049124',
 'IPR049260',
 'IPR049476',
 'IPR049636',
 'IPR049752',
 'IPR049755',
 'IPR049893',
 'IPR050004',
 'IPR050827',
 'IPR050847',
 'IPR051000',
 'IPR051493',
 'IPR051575',
 'IPR051644',
 'IPR051651',
 'IPR051969',
 'IPR052003',
 'IPR052026',
 'IPR052253',
 'IPR052509',
 'IPR052695',
 'IPR052833',
 'IPR052920',
 'IPR052931',
 'IPR053501',
 'IPR054105',
 'IPR054180',
 'IPR054505',
 'IPR054534',
 'IPR055339',
 'IPR055370',
 'IPR056342',
 'IPR056911',
 'IPR057581',
 'IPR057962',
 'IPR012677',
 'IPR000047',
 'IPR000281',
 'IPR001387',
 'IPR002577',
 'IPR004409',
 'IPR005104',
 'IPR007394',
 'IPR007737',
 'IPR011991',
 'IPR013196',
 'IPR013197',
 'IPR017895',
 'IPR019707',
 'IPR021027',
 'IPR021896',
 'IPR023120',
 'IPR024259',
 'IPR024431',
 'IPR024760',
 'IPR025736',
 'IPR027805',
 'IPR028088',
 'IPR029491',
 'IPR030828',
 'IPR032135',
 'IPR032622',
 'IPR032877',
 'IPR037392',
 'IPR038722',
 'IPR038723',
 'IPR039554',
 'IPR041068',
 'IPR041143',
 'IPR041444',
 'IPR041657',
 'IPR041687',
 'IPR042070',
 'IPR045403',
 'IPR045745',
 'IPR046783',
 'IPR046847',
 'IPR046930',
 'IPR046931',
 'IPR048671',
 'IPR048714',
 'IPR049274',
 'IPR054058',
 'IPR054448',
 'IPR055121',
 'IPR055166',
 'IPR055224',
 'IPR055245',
 'IPR055247',
 'IPR056479',
 'IPR057588',
 'IPR057842',
 'IPR057846',
 'IPR058038',
 'IPR058056',
 'IPR000962',
 'IPR003743',
 'IPR004149',
 'IPR010603',
 'IPR020458',
 'IPR020460',
 'IPR025687',
 'IPR038037',
 'IPR038366',
 'IPR039515',
 'IPR044882',
 'IPR000747',
 'IPR001356',
 'IPR003893',
 'IPR006455',
 'IPR008422',
 'IPR009057',
 'IPR020479',
 'IPR024441',
 'IPR024463',
 'IPR024978',
 'IPR039162',
 'IPR039276',
 'IPR039350',
 'IPR039775',
 'IPR042160',
 'IPR044830',
 'IPR045876',
 'IPR003150',
 'IPR003316',
 'IPR013668',
 'IPR015191',
 'IPR019391',
 'IPR033439',
 'IPR035625',
 'IPR041024',
 'IPR041885',
 'IPR042035',
 'IPR048333',
 'IPR048638',
 'IPR048907',
 'IPR048975',
 'IPR049125',
 'IPR053835',
 'IPR054020',
 'IPR054040',
 'IPR054041',
 'IPR054042',
 'IPR054317',
 'IPR054404',
 'IPR054405',
 'IPR055194',
 'IPR055207',
 'IPR055367',
 'IPR055368',
 'IPR055369',
 'IPR056428',
 'IPR056467',
 'IPR056773',
 'IPR006856',
 'IPR044601',
 'IPR047443',
 'IPR048016',
 'IPR049523',
 'IPR050140',
 'IPR051365',
 'IPR055339',
 'IPR001005',
 'IPR006447',
 'IPR007015',
 'IPR010588',
 'IPR014645',
 'IPR015010',
 'IPR015395',
 'IPR015495',
 'IPR016310',
 'IPR017930',
 'IPR024752',
 'IPR025610',
 'IPR025756',
 'IPR026095',
 'IPR026162',
 'IPR028002',
 'IPR032563',
 'IPR039467',
 'IPR040849',
 'IPR041413',
 'IPR042792',
 'IPR044597',
 'IPR044676',
 'IPR044787',
 'IPR044822',
 'IPR044895',
 'IPR045026',
 'IPR046775',
 'IPR046955',
 'IPR047240',
 'IPR049257',
 'IPR049260',
 'IPR050560',
 'IPR051575',
 'IPR052870',
 'IPR054505',
 'IPR055067',
 'IPR020983',
 'IPR000253',
 'IPR018533',
 'IPR042839',
 'IPR045912',
 'IPR047119',
 'IPR047208',
 'IPR047289',
 'IPR047364',
 'IPR047366',
 'IPR047388',
 'IPR047389',
 'IPR047391',
 'IPR047392',
 'IPR047393',
 'IPR047394',
 'IPR047397',
 'IPR047398',
 'IPR047401',
 'IPR047403',
 'IPR047404',
 'IPR047408',
 'IPR047409',
 'IPR047410',
 'IPR047412',
 'IPR047413',
 'IPR047414',
 'IPR047511',
 'IPR047512',
 'IPR047513',
 'IPR047514',
 'IPR047515',
 'IPR047516',
 'IPR047518',
 'IPR047519',
 'IPR049624',
 'IPR049779',
 'IPR050211',
 'IPR050998',
 'IPR051770',
 'IPR052328',
 'IPR052642',
 'IPR003871',
 'IPR011709',
 'IPR032076',
 'IPR038645',
 'IPR040582',
 'IPR046428',
 'IPR048426',
 'IPR048970',
 'IPR049507',
 'IPR053944',
 'IPR057620',
 'IPR000690',
 'IPR003604',
 'IPR013085',
 'IPR013087',
 'IPR017114',
 'IPR031799',
 'IPR040689',
 'IPR041661',
 'IPR041697',
 'IPR043359',
 'IPR044653',
 'IPR050169',
 'IPR050329',
 'IPR050527',
 'IPR050589',
 'IPR050636',
 'IPR050717',
 'IPR050752',
 'IPR050758',
 'IPR050826',
 'IPR050888',
 'IPR050916',
 'IPR051007',
 'IPR051565',
 'IPR051879',
 'IPR051967',
 'IPR052130',
 'IPR056345',
 'IPR056382',
 'IPR056767',
 'IPR057026',
 'IPR057038',
 'IPR057281',
 'IPR057766',
 'IPR004826',
 'IPR040223',
 'IPR043321',
 'IPR044521',
 'IPR051027',
 'IPR052483',
 'IPR001739',
 'IPR002197',
 'IPR003340',
 'IPR004191',
 'IPR004330',
 'IPR005569',
 'IPR006779',
 'IPR007889',
 'IPR008336',
 'IPR011564',
 'IPR013030',
 'IPR013034',
 'IPR014048',
 'IPR015126',
 'IPR015351',
 'IPR015358',
 'IPR015371',
 'IPR018060',
 'IPR018754',
 'IPR021068',
 'IPR021289',
 'IPR022092',
 'IPR024305',
 'IPR025898',
 'IPR029291',
 'IPR030094',
 'IPR030408',
 'IPR031900',
 'IPR036202',
 'IPR036217',
 'IPR037095',
 'IPR037392',
 'IPR040586',
 'IPR040724',
 'IPR040725',
 'IPR040731',
 'IPR043031',
 'IPR045303',
 'IPR048664',
 'IPR048715',
 'IPR048970',
 'IPR054406',
 'IPR001827',
 'IPR003106',
 'IPR006456',
 'IPR016233',
 'IPR017112',
 'IPR017970',
 'IPR017995',
 'IPR019549',
 'IPR019737',
 'IPR021918',
 'IPR022067',
 'IPR022132',
 'IPR022135',
 'IPR024578',
 'IPR031701',
 'IPR032453',
 'IPR038861',
 'IPR039325',
 'IPR040363',
 'IPR040960',
 'IPR042191',
 'IPR042223',
 'IPR042247',
 'IPR042412',
 'IPR042634',
 'IPR042768',
 'IPR042917',
 'IPR042982',
 'IPR042988',
 'IPR043265',
 'IPR043378',
 'IPR043402',
 'IPR043562',
 'IPR044186',
 'IPR044557',
 'IPR044558',
 'IPR044559',
 'IPR044977',
 'IPR045224',
 'IPR046327',
 'IPR046333',
 'IPR047152',
 'IPR047956',
 'IPR049593',
 'IPR049594',
 'IPR050224',
 'IPR050296',
 'IPR050394',
 'IPR050453',
 'IPR050460',
 'IPR050609',
 'IPR050649',
 'IPR050674',
 'IPR050720',
 'IPR050762',
 'IPR050803',
 'IPR050848',
 'IPR050877',
 'IPR050948',
 'IPR051000',
 'IPR051003',
 'IPR051300',
 'IPR051306',
 'IPR051440',
 'IPR051574',
 'IPR051649',
 'IPR051662',
 'IPR051775',
 'IPR051895',
 'IPR051968',
 'IPR052002',
 'IPR052145',
 'IPR052294',
 'IPR052488',
 'IPR052497',
 'IPR052631',
 'IPR053300',
 'IPR056559',
 'IPR056560',
 'IPR057287']

In [7]:
# 파일 리스트 수집
rna_files = glob.glob('/Users/khj/Desktop/Project_ongoing/DRBP/data/DRBP_result_analysis/Binding_info/IPR_binding_info/RNA-binding_domain_IPR/*.tsv')  # 디렉토리 경로를 원하는 경로로 수정

# 각 파일을 읽어서 리스트에 담기
rna_df_list = [pd.read_csv(f, sep='\t') for f in rna_files]

# 하나의 DataFrame으로 합치기
rna_combined_df = pd.concat(rna_df_list, ignore_index=True)

# (선택) index 리셋
rna_combined_df.reset_index(drop=True, inplace=True)
RBP_IPR_list = list(rna_combined_df['Accession'])
len(RBP_IPR_list)

853

In [8]:
len(RBP_IPR_list)

853

In [3]:
# 파일 리스트 수집
dna_GO_files = glob.glob('/Users/khj/Desktop/Project_ongoing/DRBP/data/DRBP_result_analysis/Binding_info/GO_binding_info/DNA_binding_GO/*.json')  # 디렉토리 경로를 원하는 경로로 수정

# 각 파일을 읽어서 리스트에 담기
dna_GO_df_list = [pd.read_json(f) for f in dna_GO_files]
dna_merged_df = pd.concat(dna_GO_df_list, ignore_index=True)
dna_merged_df['id'] = dna_merged_df['results'].apply(lambda x: x.get('id') if isinstance(x, dict) else None)
dna_merged_df['descendants'] = dna_merged_df['results'].apply(lambda x: x.get('descendants') if isinstance(x, dict) else None)
dna_expanded_df = dna_merged_df.explode('descendants', ignore_index=True)
DNA_Binding_GO_list = list(dna_expanded_df['id'])+list(dna_expanded_df['descendants'])
DNA_Binding_GO_list = list(set(DNA_Binding_GO_list))
DNA_Binding_GO_list

['GO:0003682',
 'GO:0032143',
 'GO:0001162',
 'GO:0000978',
 'GO:0032358',
 'GO:0016987',
 'GO:0044374',
 'GO:1990470',
 'GO:0032135',
 'GO:0045142',
 'GO:0001161',
 'GO:0035485',
 'GO:0003691',
 'GO:0043035',
 'GO:0032139',
 'GO:0000981',
 'GO:0106250',
 'GO:0045027',
 'GO:0044323',
 'GO:0044377',
 'GO:0000182',
 'GO:0001147',
 'GO:0003696',
 'GO:0071820',
 'GO:0035939',
 'GO:0097100',
 'GO:1990471',
 'GO:0008327',
 'GO:0032141',
 'GO:0035484',
 'GO:0001228',
 'GO:0032131',
 'GO:0070336',
 'GO:0000976',
 'GO:0003692',
 'GO:0000992',
 'GO:0070594',
 'GO:0098531',
 'GO:0030983',
 'GO:0031963',
 'GO:0043110',
 'GO:0140431',
 'GO:0045322',
 'GO:0032181',
 'GO:0003690',
 'GO:0003688',
 'GO:1990837',
 'GO:0003681',
 'GO:0032357',
 'GO:0019237',
 'GO:0032142',
 'GO:0003677',
 'GO:0035487',
 'GO:0000403',
 'GO:0031491',
 'GO:0141180',
 'GO:0098505',
 'GO:0003707',
 'GO:0004883',
 'GO:0003700',
 'GO:0036310',
 'GO:0000404',
 'GO:0140728',
 'GO:0044729',
 'GO:0035486',
 'GO:0000332',
 'GO:1990943',
 'GO:0001039',
 'GO:0070338',
 'GO:0004879',
 'GO:0035538',
 'GO:1990829',
 'GO:0010385',
 'GO:0001163',
 'GO:0001217',
 'GO:0141097',
 'GO:0097030',
 'GO:0042162',
 'GO:0031490',
 'GO:0044378',
 'GO:0032136',
 'GO:0001216',
 'GO:0140586',
 'GO:0043047',
 'GO:0000401',
 'GO:0001046',
 'GO:0008301',
 'GO:0032810',
 'GO:0030284',
 'GO:1990472',
 'GO:0141094',
 'GO:0001003',
 'GO:0110035',
 'GO:0001002',
 'GO:0000405',
 'GO:0001165',
 'GO:0031634',
 'GO:0003680',
 'GO:0000402',
 'GO:0001006',
 'GO:0001227',
 'GO:0080084',
 'GO:0003693',
 'GO:1990955',
 'GO:0001018',
 'GO:0000406',
 'GO:0140587',
 'GO:0000497',
 'GO:0140585',
 'GO:0034056',
 'GO:0000977',
 'GO:0001019',
 'GO:0061849',
 'GO:0032422',
 'GO:0010736',
 'GO:0070644',
 'GO:0032132',
 'GO:0000217',
 'GO:1990165',
 'GO:0141096',
 'GO:0031492',
 'GO:0032356',
 'GO:0090655',
 'GO:0010844',
 'GO:0061776',
 'GO:0003684',
 'GO:1990841',
 'GO:0038186',
 'GO:0000987',
 'GO:0035497',
 'GO:0032140',
 'GO:0070888',
 'GO:0032138',
 'GO:0061821',
 'GO:0000400',
 'GO:0032448',
 'GO:0106260',
 'GO:0035488',
 'GO:0062037',
 'GO:0099077',
 'GO:0071443',
 'GO:0003697',
 'GO:0051880',
 'GO:0035489',
 'GO:1990188',
 'GO:0001016',
 'GO:0000979',
 'GO:0061730',
 'GO:1990814',
 'GO:0070337',
 'GO:1905773',
 'GO:0043565',
 'GO:0001164',
 'GO:0098847',
 'GO:0032137']

In [4]:
# 파일 리스트 수집
rna_GO_files = glob.glob('/Users/khj/Desktop/Project_ongoing/DRBP/data/DRBP_result_analysis/Binding_info/GO_binding_info/RNA_binding_GO/*.json')  # 디렉토리 경로를 원하는 경로로 수정

# 각 파일을 읽어서 리스트에 담기
rna_GO_df_list = [pd.read_json(f) for f in rna_GO_files]
rna_merged_df = pd.concat(rna_GO_df_list, ignore_index=True)
rna_merged_df['id'] = rna_merged_df['results'].apply(lambda x: x.get('id') if isinstance(x, dict) else None)
rna_merged_df['descendants'] = rna_merged_df['results'].apply(lambda x: x.get('descendants') if isinstance(x, dict) else None)
rna_expanded_df = rna_merged_df.explode('descendants', ignore_index=True)
RNA_Binding_GO_list = list(rna_expanded_df['id'])+list(rna_expanded_df['descendants'])
RNA_Binding_GO_list = list(set(RNA_Binding_GO_list))
RNA_Binding_GO_list

['GO:0033435',
 'GO:0070147',
 'GO:0034511',
 'GO:0016433',
 'GO:0030621',
 'GO:0033677',
 'GO:0006364',
 'GO:0000292',
 'GO:0160141',
 'GO:0002943',
 'GO:0180037',
 'GO:0070711',
 'GO:0004479',
 'GO:0033401',
 'GO:0032296',
 'GO:0000457',
 'GO:0000964',
 'GO:0071047',
 'GO:0070708',
 'GO:0000450',
 'GO:0004831',
 'GO:0000349',
 'GO:0141102',
 'GO:0000488',
 'GO:0070475',
 'GO:1901259',
 'GO:0043906',
 'GO:0000474',
 'GO:0000956',
 'GO:0033428',
 'GO:0071051',
 'GO:0000966',
 'GO:0034583',
 'GO:0050560',
 'GO:0033453',
 'GO:0033463',
 'GO:0016076',
 'GO:0098620',
 'GO:0008847',
 'GO:0035279',
 'GO:0110104',
 'GO:0071044',
 'GO:0000379',
 'GO:1900864',
 'GO:0033419',
 'GO:0031990',
 'GO:0006383',
 'GO:0006351',
 'GO:2000827',
 'GO:0033899',
 'GO:0001734',
 'GO:0006402',
 'GO:0000963',
 'GO:0000387',
 'GO:0052927',
 'GO:0070966',
 'GO:0034227',
 'GO:0004823',
 'GO:0002143',
 'GO:0006405',
 'GO:0000378',
 'GO:0141217',
 'GO:0033430',
 'GO:0062152',
 'GO:0140101',
 'GO:0009300',
 'GO:0033407',
 'GO:0000049',
 'GO:0160239',
 'GO:0062105',
 'GO:0001139',
 'GO:0030560',
 'GO:0031426',
 'GO:0006392',
 'GO:0016078',
 'GO:0043634',
 'GO:1990515',
 'GO:0035946',
 'GO:0039703',
 'GO:0110064',
 'GO:0030558',
 'GO:0019091',
 'GO:0140098',
 'GO:0071207',
 'GO:0110105',
 'GO:0000494',
 'GO:0035598',
 'GO:0000470',
 'GO:0050567',
 'GO:0042789',
 'GO:0070712',
 'GO:0071030',
 'GO:0046595',
 'GO:0160147',
 'GO:0010267',
 'GO:0070180',
 'GO:1990605',
 'GO:0033440',
 'GO:0000481',
 'GO:0031167',
 'GO:0160091',
 'GO:0042791',
 'GO:0106340',
 'GO:0043767',
 'GO:0034585',
 'GO:0070152',
 'GO:0002926',
 'GO:0000171',
 'GO:0033415',
 'GO:0016430',
 'GO:0160230',
 'GO:0102524',
 'GO:0052907',
 'GO:0160154',
 'GO:0180034',
 'GO:0033464',
 'GO:0031123',
 'GO:0071039',
 'GO:0043688',
 'GO:0070681',
 'GO:0003725',
 'GO:0006404',
 'GO:0042778',
 'GO:0002153',
 'GO:1990432',
 'GO:0016973',
 'GO:0160240',
 'GO:0048027',
 'GO:0090666',
 'GO:0045815',
 'GO:0052913',
 'GO:1903241',
 'GO:0090625',
 'GO:0031591',
 'GO:0060812',
 'GO:0002927',
 'GO:0102262',
 'GO:1990514',
 'GO:0160152',
 'GO:0006386',
 'GO:0180036',
 'GO:0071041',
 'GO:0002100',
 'GO:0070479',
 'GO:0032574',
 'GO:0008143',
 'GO:0004819',
 'GO:0002161',
 'GO:0043867',
 'GO:0002106',
 'GO:0031126',
 'GO:0036317',
 'GO:0071045',
 'GO:0071042',
 'GO:0141125',
 'GO:0071028',
 'GO:0052914',
 'GO:0016556',
 'GO:0006401',
 'GO:0000463',
 'GO:0070897',
 'GO:0035194',
 'GO:0046594',
 'GO:0008988',
 'GO:0004830',
 'GO:0036450',
 'GO:1990984',
 'GO:0043908',
 'GO:0102265',
 'GO:0051029',
 'GO:0033893',
 'GO:0000455',
 'GO:0001112',
 'GO:0033420',
 'GO:1990261',
 'GO:0033902',
 'GO:0141100',
 'GO:0008883',
 'GO:0006390',
 'GO:0001195',
 'GO:0035198',
 'GO:0160137',
 'GO:0004817',
 'GO:0006418',
 'GO:0006363',
 'GO:0180018',
 'GO:0070900',
 'GO:0033445',
 'GO:0017070',
 'GO:0043828',
 'GO:0033454',
 'GO:0070158',
 'GO:0160143',
 'GO:0039690',
 'GO:0090624',
 'GO:0032267',
 'GO:0080178',
 'GO:0035760',
 'GO:0016891',
 'GO:0070705',
 'GO:0033439',
 'GO:0031124',
 'GO:0003729',
 'GO:0030515',
 'GO:0030565',
 'GO:0160117',
 'GO:0040031',
 'GO:0070707',
 'GO:0001682',
 'GO:0160105',
 'GO:0006368',
 'GO:0070901',
 'GO:0000354',
 'GO:0090685',
 'GO:0051391',
 'GO:0046589',
 'GO:0008173',
 'GO:0009301',
 'GO:0004827',
 'GO:0004810',
 'GO:0033894',
 'GO:0000479',
 'GO:0004824',
 'GO:0061475',
 'GO:0004816',
 'GO:0097157',
 'GO:0008989',
 'GO:0033425',
 'GO:0033979',
 'GO:0016553',
 'GO:1990825',
 'GO:0140818',
 'GO:0016180',
 'GO:0000489',
 'GO:0071424',
 'GO:0002942',
 'GO:0036002',
 'GO:0035928',
 'GO:0070159',
 'GO:0002935',
 'GO:0000477',
 'GO:0045131',
 'GO:0008419',
 'GO:0001164',
 'GO:0034513',
 'GO:0033414',
 'GO:0070184',
 'GO:0120159',
 'GO:0071038',
 'GO:0106410',
 'GO:0000957',
 'GO:0160101',
 'GO:0160103',
 'GO:0044748',
 'GO:0140742',
 'GO:0016251',
 'GO:0031054',
 'GO:0000184',
 'GO:0008187',
 'GO:0000366',
 'GO:0039692',
 'GO:0106388',
 'GO:0016422',
 'GO:0000350',
 'GO:0033456',
 'GO:0001720',
 'GO:0003899',
 'GO:0016070',
 'GO:0047151',
 'GO:0070038',
 'GO:0034472',
 'GO:0016423',
 'GO:0006422',
 'GO:0009304',
 'GO:0033897',
 'GO:0000995',
 'GO:0033438',
 'GO:0051236',
 'GO:0070145',
 'GO:0006396',
 'GO:0000483',
 'GO:0016074',
 'GO:0001172',
 'GO:0001174',
 'GO:0034062',
 'GO:0003963',
 'GO:1904812',
 'GO:0000340',
 'GO:0000372',
 'GO:0090671',
 'GO:0019843',
 'GO:0001147',
 'GO:0008312',
 'GO:0033901',
 'GO:0006353',
 'GO:0070899',
 'GO:0070148',
 'GO:0016428',
 'GO:0000451',
 'GO:0002940',
 'GO:0010599',
 'GO:0033204',
 'GO:1990074',
 'GO:0008334',
 'GO:0031070',
 'GO:1990273',
 'GO:0006398',
 'GO:0002946',
 'GO:1990276',
 'GO:0098851',
 'GO:0001059',
 'GO:0106354',
 'GO:0060810',
 'GO:1903469',
 'GO:0009302',
 'GO:0000377',
 'GO:0051034',
 'GO:0000486',
 'GO:0006369',
 'GO:0106335',
 'GO:0030743',
 'GO:0006367',
 'GO:0002949',
 'GO:0033448',
 'GO:0052929',
 'GO:0016892',
 'GO:0110152',
 'GO:0004815',
 'GO:1990931',
 'GO:0036261',
 'GO:0045301',
 'GO:0033452',
 'GO:0000213',
 'GO:0006434',
 'GO:0043907',
 'GO:0106029',
 'GO:0000465',
 'GO:0006352',
 'GO:0034475',
 'GO:0002101',
 'GO:0030627',
 'GO:0006397',
 'GO:0050566',
 'GO:0008452',
 'GO:1990762',
 'GO:0030566',
 'GO:0000461',
 'GO:0001111',
 'GO:0008990',
 'GO:0033442',
 'GO:0006431',
 'GO:0033404',
 'GO:0033437',
 'GO:0035197',
 'GO:0001068',
 'GO:0004483',
 'GO:0071040',
 'GO:0051237',
 'GO:0010609',
 'GO:0016438',
 'GO:0120550',
 'GO:0016435',
 'GO:0035278',
 'GO:0008251',
 'GO:0030598',
 'GO:0043827',
 'GO:0042797',
 'GO:0006435',
 'GO:0030597',
 'GO:0033417',
 'GO:0006354',
 'GO:0000495',
 'GO:0033450',
 'GO:0052719',
 'GO:0033434',
 'GO:0033402',
 'GO:0006429',
 'GO:0006385',
 'GO:0097393',
 'GO:0000375',
 'GO:0001069',
 'GO:0004525',
 'GO:0019988',
 'GO:0019092',
 'GO:0004812',
 'GO:0180011',
 'GO:0050561',
 'GO:0004125',
 'GO:1990400',
 'GO:0052735',
 'GO:0160151',
 'GO:0033459',
 'GO:0006425',
 'GO:0030533',
 'GO:0004535',
 'GO:0000959',
 'GO:0006382',
 'GO:0102267',
 'GO:0034964',
 'GO:0033449',
 'GO:0050658',
 'GO:0006399',
 'GO:0006366',
 'GO:0040033',
 'GO:0061752',
 'GO:0035614',
 'GO:0106346',
 'GO:0160149',
 'GO:0070714',
 'GO:0140746',
 'GO:0070329',
 'GO:0033227',
 'GO:0071208',
 'GO:0070481',
 'GO:0002107',
 'GO:0052717',
 'GO:0036453',
 'GO:0035927',
 'GO:0043766',
 'GO:0000288',
 'GO:0006428',
 'GO:0071043',
 'GO:0140235',
 'GO:0002099',
 'GO:0009299',
 'GO:0001014',
 'GO:0033890',
 'GO:0035613',
 'GO:0035719',
 'GO:0052906',
 'GO:0006393',
 'GO:0000215',
 'GO:0070476',
 'GO:0033403',
 'GO:0043628',
 'GO:0032774',
 'GO:0019093',
 'GO:1990417',
 'GO:0106222',
 'GO:0070680',
 'GO:0000394',
 'GO:0034246',
 'GO:0070183',
 'GO:0061614',
 'GO:0180012',
 'GO:0052905',
 'GO:0097694',
 'GO:0120048',
 'GO:0000487',
 'GO:0003727',
 'GO:0033405',
 'GO:0006370',
 'GO:0052908',
 'GO:0000175',
 'GO:0006361',
 'GO:0051028',
 'GO:0090670',
 'GO:0051075',
 'GO:0000462',
 'GO:0097745',
 'GO:0000290',
 'GO:0033896',
 'GO:0016031',
 'GO:0033444',
 'GO:0001192',
 'GO:0033678',
 'GO:0001118',
 'GO:0001113',
 'GO:0160090',
 'GO:0110153',
 'GO:0070157',
 'GO:0030562',
 'GO:0098680',
 'GO:0000393',
 'GO:0003968',
 'GO:0000454',
 'GO:0016434',
 'GO:0140541',
 'GO:0090646',
 'GO:1900865',
 'GO:0051030',
 'GO:0106050',
 'GO:0052912',
 'GO:0000485',
 'GO:0070146',
 'GO:0045450',
 'GO:0016436',
 'GO:0036307',
 'GO:0030559',
 'GO:0052915',
 'GO:0002131',
 'GO:0019097',
 'GO:0000245',
 'GO:0030626',
 'GO:0009451',
 'GO:0019096',
 'GO:0000448',
 'GO:0070902',
 'GO:0102263',
 'GO:0097158',
 'GO:0006360',
 'GO:0103016',
 'GO:0000384',
 'GO:0033679',
 'GO:0002105',
 'GO:0060813',
 'GO:0006424',
 'GO:0004828',
 'GO:0039689',
 'GO:0070878',
 'GO:0004814',
 'GO:0070034',
 'GO:0160139',
 'GO:0008650',
 'GO:0039691',
 'GO:0140958',
 'GO:0004829',
 'GO:0002129',
 'GO:0016554',
 'GO:0042790',
 'GO:0140432',
 'GO:0098621',
 'GO:0000294',
 'GO:0043145',
 'GO:0102266',
 'GO:0001182',
 'GO:0016896',
 'GO:0071034',
 'GO:0004057',
 'GO:0098618',
 'GO:0007316',
 'GO:0000365',
 'GO:0019090',
 'GO:0000458',
 'GO:0006388',
 'GO:0002108',
 'GO:0070181',
 'GO:0000154',
 'GO:0070549',
 'GO:0042781',
 'GO:0004534',
 'GO:0106261',
 'GO:0002128',
 'GO:0000398',
 'GO:0034458',
 'GO:0000464',
 'GO:0070709',
 'GO:0034247',
 'GO:0140226',
 'GO:0033432',
 'GO:0031118',
 'GO:0070040',
 'GO:0034353',
 'GO:0097697',
 'GO:0033431',
 'GO:0106004',
 'GO:0033418',
 'GO:0070039',
 'GO:0043633',
 'GO:0000471',
 'GO:0031086',
 'GO:0006269',
 'GO:0030555',
 'GO:0006427',
 'GO:0000476',
 'GO:0002109',
 'GO:0004825',
 'GO:0070156',
 'GO:0008859',
 'GO:0031125',
 'GO:0070144',
 'GO:0102522',
 'GO:0016432',
 'GO:0070710',
 'GO:0070150',
 'GO:0016071',
 'GO:0106347',
 'GO:0016073',
 'GO:0008033',
 'GO:1990481',
 'GO:0051033',
 'GO:0016300',
 'GO:0033462',
 'GO:0009303',
 'GO:0006409',
 'GO:0033446',
 'GO:0070154',
 'GO:0034336',
 'GO:0048254',
 'GO:0089715',
 'GO:0160106',
 'GO:0050265',
 'GO:0001175',
 'GO:1990715',
 'GO:0030629',
 'GO:0034473',
 'GO:0034046',
 'GO:0000388',
 'GO:1900871',
 'GO:0106105',
 'GO:0120049',
 'GO:0034477',
 'GO:0001193',
 'GO:0033461',
 'GO:0030624',
 'GO:0036260',
 'GO:0106074',
 'GO:0004522',
 'GO:0001109',
 'GO:0160136',
 'GO:0106032',
 'GO:0035597',
 'GO:0016427',
 'GO:0070478',
 'GO:0140102',
 'GO:0001015',
 'GO:0071209',
 'GO:0008914',
 'GO:0035515',
 'GO:0033426',
 'GO:0033412',
 'GO:0102521',
 'GO:0071036',
 'GO:0030625',
 'GO:0051123',
 'GO:0004818',
 'GO:0000376',
 'GO:0002939',
 'GO:0000373',
 'GO:1990983',
 'GO:0004484',
 'GO:1990280',
 'GO:0001188',
 'GO:0070041',
 'GO:0042780',
 'GO:1990970',
 'GO:0070143',
 'GO:0140745',
 'GO:0039694',
 'GO:0033406',
 'GO:0160138',
 'GO:0042868',
 'GO:0033460',
 'GO:0002097',
 'GO:0097322',
 'GO:0034403',
 'GO:0070155',
 'GO:0030563',
 'GO:0070525',
 'GO:0043915',
 'GO:0071046',
 'GO:0008479',
 'GO:0072670',
 'GO:0042795',
 'GO:0097222',
 'GO:0033441',
 'GO:0070043',
 'GO:0006421',
 'GO:0033967',
 'GO:0000339',
 'GO:0002127',
 'GO:0000341',
 'GO:0043905',
 'GO:0035513',
 'GO:0140991',
 'GO:0002151',
 'GO:0009022',
 'GO:1990431',
 'GO:0033900',
 'GO:0160102',
 'GO:0004826',
 'GO:0008649',
 'GO:0008176',
 'GO:0030564',
 'GO:0006408',
 'GO:0004045',
 'GO:0061980',
 'GO:0001717',
 'GO:0016072',
 'GO:0035281',
 'GO:0052909',
 'GO:0035368',
 'GO:0061716',
 'GO:0001060',
 'GO:1990882',
 'GO:0003724',
 'GO:0097747',
 'GO:0090617',
 'GO:0090615',
 'GO:1990428',
 'GO:0030488',
 'GO:0004526',
 'GO:0160236',
 'GO:0180031',
 'GO:0071032',
 'GO:0006420',
 'GO:0160016',
 'GO:0070153',
 'GO:0000348',
 'GO:0008192',
 'GO:0009452',
 'GO:0033429',
 'GO:0000389',
 'GO:0008266',
 'GO:0106348',
 'GO:1990174',
 'GO:0071035',
 'GO:0051214',
 'GO:0030557',
 'GO:0033621',
 'GO:0035945',
 'GO:0002132',
 'GO:0000475',
 'GO:0043685',
 'GO:0160118',
 'GO:0006423',
 'GO:0052916',
 'GO:0033413',
 'GO:0042134',
 'GO:0160206',
 'GO:0070054',
 'GO:0016077',
 'GO:0000289',
 'GO:0060811',
 'GO:0036308',
 'GO:0004532',
 'GO:0000466',
 'GO:0006384',
 'GO:0030620',
 'GO:0030422',
 'GO:0160140',
 'GO:0004832',
 'GO:0070717',
 'GO:0006376',
 'GO:0097358',
 'GO:0000472',
 'GO:0090672',
 'GO:0004533',
 'GO:0009616',
 'GO:0170057',
 'GO:0045291',
 'GO:0004821',
 'GO:0080156',
 'GO:0006433',
 'GO:0099116',
 'GO:0002937',
 'GO:0042245',
 'GO:0071951',
 'GO:0110154',
 'GO:0071952',
 'GO:0004523',
 'GO:0035925',
 'GO:0031119',
 'GO:0033436',
 'GO:1990932',
 'GO:0110155',
 'GO:0019094',
 'GO:0000480',
 'GO:0001522',
 'GO:0017150',
 'GO:0043822',
 'GO:0034512',
 'GO:0140040',
 'GO:0061953',
 'GO:0061016',
 'GO:0000342',
 'GO:0070151',
 'GO:0000179',
 'GO:0070706',
 'GO:0106217',
 'GO:0031120',
 'GO:0042835',
 'GO:0033451',
 'GO:0004808',
 'GO:0000968',
 'GO:0043137',
 'GO:0106026',
 'GO:1990930',
 'GO:0070185',
 'GO:0001173',
 'GO:0006391',
 'GO:0070651',
 'GO:0030847',
 'GO:0001110',
 'GO:0160248',
 'GO:0008995',
 'GO:0140766',
 'GO:0042793',
 'GO:0043399',
 'GO:0033592',
 'GO:0006362',
 'GO:0033408',
 'GO:1904678',
 'GO:0160142',
 'GO:0052381',
 'GO:0000390',
 'GO:0017130',
 'GO:0004813',
 'GO:0043829',
 'GO:0006419',
 'GO:1990838',
 'GO:0034586',
 'GO:0000048',
 'GO:0019095',
 'GO:0140223',
 'GO:0160148',
 'GO:0008097',
 'GO:0006437',
 'GO:0042794',
 'GO:0097748',
 'GO:0031053',
 'GO:0000482',
 'GO:0071164',
 'GO:0004820',
 'GO:0030350',
 'GO:0071031',
 'GO:0070127',
 'GO:0061708',
 'GO:0044747',
 'GO:0070037',
 'GO:0051392',
 'GO:0051031',
 'GO:1990438',
 'GO:0008380',
 'GO:0035600',
 'GO:0031087',
 'GO:0004521',
 'GO:0140990',
 'GO:0052911',
 'GO:0140673',
 'GO:0140741',
 'GO:1903231',
 'GO:0033410',
 'GO:0098808',
 'GO:0061015',
 'GO:0070677',
 'GO:0006400',
 'GO:0000244',
 'GO:0160104',
 'GO:0004540',
 'GO:0000386',
 'GO:0090486',
 'GO:0071528',
 'GO:0033447',
 'GO:0033421',
 'GO:0106349',
 'GO:0180035',
 'GO:0033416',
 'GO:0052910',
 'GO:0000449',
 'GO:0000447',
 'GO:0141065',
 'GO:0160153',
 'GO:0090616',
 'GO:0140023',
 'GO:0002196',
 'GO:0002098',
 'GO:0010239',
 'GO:0003972',
 'GO:0002130',
 'GO:0033411',
 'GO:0106059',
 'GO:0030846',
 'GO:1990799',
 'GO:0000395',
 'GO:0017069',
 'GO:0033458',
 'GO:0033455',
 'GO:0141098',
 'GO:0141101',
 'GO:0102264',
 'GO:0030622',
 'GO:0042796',
 'GO:0180021',
 'GO:0180010',
 'GO:0033427',
 'GO:0003723',
 'GO:0106005',
 'GO:0000460',
 'GO:0106142',
 'GO:0140869',
 'GO:0000512',
 'GO:0010495',
 'GO:0004482',
 'GO:0070042',
 'GO:0006426',
 'GO:0045292',
 'GO:0006432',
 'GO:0034584',
 'GO:0051499',
 'GO:0000468',
 'GO:0033895',
 'GO:0034474',
 'GO:0033457',
 'GO:0035195',
 'GO:0033422',
 'GO:0001510',
 'GO:0070149',
 'GO:0036265',
 'GO:0030619',
 'GO:0002104',
 'GO:0000967',
 'GO:0044029',
 'GO:0006438',
 'GO:0035196',
 'GO:0008098',
 'GO:0000352',
 'GO:0140965',
 'GO:1990884',
 'GO:0002938',
 'GO:0001680',
 'GO:0033443',
 'GO:0002136',
 'GO:0006403',
 'GO:0071026',
 'GO:0071027',
 'GO:0098619',
 'GO:0001181',
 'GO:0000958',
 'GO:0016075',
 'GO:0160107',
 'GO:0051500',
 'GO:0043039',
 'GO:0008193',
 'GO:0030561',
 'GO:0004549',
 'GO:0071037',
 'GO:0000380',
 'GO:0004730',
 'GO:0071025',
 'GO:0141009',
 'GO:0002110',
 'GO:0061504',
 'GO:1990180',
 'GO:0043144',
 'GO:0003730',
 'GO:0006430',
 'GO:0160150',
 'GO:0033433',
 'GO:0000452',
 'GO:0017131',
 'GO:0070898',
 'GO:0034966',
 'GO:0010587',
 'GO:0034476',
 'GO:0000353',
 'GO:0034965',
 'GO:0070883',
 'GO:0061503',
 'GO:0140891',
 'GO:0030623',
 'GO:0030628',
 'GO:0030490',
 'GO:0043040',
 'GO:0006406',
 'GO:0006436',
 'GO:0000473',
 'GO:0000374',
 'GO:0008174',
 'GO:0033409',
 'GO:0004822',
 'GO:0034963',
 'GO:0110156',
 'GO:0043816',
 'GO:0051215',
 'GO:0002103',
 'GO:0008298',
 'GO:0031425',
 'GO:0008175',
 'GO:0033423',
 'GO:0045451',
 'GO:0070713',
 'GO:0010586',
 'GO:0000467',
 'GO:0016426',
 'GO:0009383',
 'GO:0033424',
 'GO:1990437',
 'GO:0034587',
 'GO:0000965',
 'GO:0062104',
 'GO:0070918',
 'GO:0060814',
 'GO:1990856',
 'GO:0016555',
 'GO:0030556',
 'GO:0070903',
 'GO:0030697',
 'GO:0000484',
 'GO:0070551',
 'GO:0034057']

In [6]:
DNA_IPR_GO_binding = interproscan[
    #(interproscan[11].isin(DBP_IPR_list)) |
    (interproscan[13].astype(str).apply(lambda x: any(go in x for go in DNA_Binding_GO_list)))
]
DNA_IPR_GO_binding

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
381,ENSP00000357556,3c2a5624677871aac9d61cae013b539c,258,SMART,SM00389,HOX_1,91,153,2.6E-25,T,05-07-2025,IPR001356,Homeodomain,GO:0003677(InterPro),-
383,ENSP00000357556,3c2a5624677871aac9d61cae013b539c,258,ProSitePatterns,PS00027,'Homeobox' domain signature.,124,147,-,T,05-07-2025,IPR017970,"Homeobox, conserved site",GO:0000981(InterPro)|GO:0006355(InterPro),-
386,ENSP00000357556,3c2a5624677871aac9d61cae013b539c,258,ProSiteProfiles,PS50071,'Homeobox' domain profile.,89,149,19.629128,T,05-07-2025,IPR001356,Homeodomain,GO:0003677(InterPro),-
387,ENSP00000357556,3c2a5624677871aac9d61cae013b539c,258,Pfam,PF00046,Homeodomain,93,148,7.3E-18,T,05-07-2025,IPR001356,Homeodomain,GO:0003677(InterPro),-
389,ENSP00000357556,3c2a5624677871aac9d61cae013b539c,258,CDD,cd00086,homeodomain,92,150,4.01581E-25,T,05-07-2025,IPR001356,Homeodomain,GO:0003677(InterPro),-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387911,ENSP00000380197,7dab597678a64172d368fa8bf4e1f183,237,Pfam,PF03131,bZIP Maf transcription factor,132,222,2.4E-27,T,05-07-2025,IPR004826,"Basic leucine zipper domain, Maf-type",GO:0003677(InterPro)|GO:0006355(InterPro),-
387914,ENSP00000380197,7dab597678a64172d368fa8bf4e1f183,237,SUPERFAMILY,SSF47454,A DNA-binding domain in eukaryotic transcripti...,132,172,1.83E-16,T,05-07-2025,IPR008917,"Transcription factor, Skn-1-like, DNA-binding ...",GO:0003677(InterPro)|GO:0006355(InterPro),-
387917,ENSP00000380197,7dab597678a64172d368fa8bf4e1f183,237,PANTHER,PTHR10129,TRANSCRIPTION FACTOR MAF,3,224,4.6E-74,T,05-07-2025,IPR024874,Transcription factor Maf family,GO:0000978(PANTHER)|GO:0000981(PANTHER)|GO:000...,-
387918,ENSP00000380197,7dab597678a64172d368fa8bf4e1f183,237,SMART,SM00338,brlzneu,157,221,1.8E-4,T,05-07-2025,IPR004827,Basic-leucine zipper domain,GO:0003700(InterPro)|GO:0006355(InterPro),-
387919,ENSP00000380197,7dab597678a64172d368fa8bf4e1f183,237,SUPERFAMILY,SSF57959,Leucine zipper domain,160,214,2.39E-5,T,05-07-2025,IPR046347,Basic-leucine zipper domain superfamily,GO:0003700(InterPro)|GO:0006355(InterPro),-

In [7]:
DNA_IPR_GO_binding.drop_duplicates(subset=0)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
381,ENSP00000357556,3c2a5624677871aac9d61cae013b539c,258,SMART,SM00389,HOX_1,91,153,2.6E-25,T,05-07-2025,IPR001356,Homeodomain,GO:0003677(InterPro),-
422,ENSP00000450607,d960c66eea311cc948947df01cac1877,1208,PANTHER,PTHR22940,TIMEOUT/TIMELESS-2,6,1184,0.0,T,05-07-2025,IPR044998,Timeless,GO:0000076(PANTHER)|GO:0003677(PANTHER)|GO:000...,-
751,ENSP00000332194,666235cc52a5f32dcbca21521af91610,129,PRINTS,PR00620,Histone H2A signature,58,71,1.6E-55,T,05-07-2025,IPR002119,Histone H2A,GO:0000786(InterPro)|GO:0003677(InterPro)|GO:0...,-
1080,ENSP00000263253,0e71c4fd26c809785655f6adc9a2b50a,2414,PANTHER,PTHR13808,CBP/P300-RELATED,9,683,0.0,T,05-07-2025,IPR013178,Histone acetyltransferase Rtt109/CBP,GO:0000123(PANTHER)|GO:0003713(PANTHER)|GO:000...,-
1098,ENSP00000379051,142bd778a2fa08786bed4005f9f50dfd,312,Pfam,PF04845,PurA ssDNA and RNA-binding protein,31,279,6.4E-93,T,05-07-2025,IPR006628,Purine-rich element binding protein family,GO:0000977(InterPro)|GO:0032422(InterPro),-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386726,ENSP00000371940,53af7feeeab068efe0afc909358126f1,439,ProSitePatterns,PS00658,Fork head domain signature 2.,148,154,-,T,05-07-2025,IPR030456,Fork head domain conserved site 2,GO:0003700(InterPro)|GO:0006355(InterPro)|GO:0...,-
386846,ENSP00000478056,c898264c86266842ae55238d7b0e0eeb,419,PANTHER,PTHR24404,ZINC FINGER PROTEIN,81,415,6.5E-31,T,05-07-2025,IPR050589,Ikaros C2H2-type zinc-finger,GO:0000978(PANTHER)|GO:0003700(PANTHER)|GO:000...,-
387360,ENSP00000435835,ebece08a5854f07a94ff4b307f30bd4b,322,Pfam,PF00178,Ets-domain,230,310,3.1E-29,T,05-07-2025,IPR000418,Ets domain,GO:0003700(InterPro)|GO:0006355(InterPro)|GO:0...,-
387585,ENSP00000344724,3c35892f4d40a86a2e927df3ae0c29bb,506,PANTHER,PTHR45781,AGAP000281-PA,1,495,1.1E-188,T,05-07-2025,IPR051365,TOX high mobility group box domain-containing ...,GO:0005634(PANTHER)|GO:0006357(PANTHER)|GO:003...,-
387909,ENSP00000380197,7dab597678a64172d368fa8bf4e1f183,237,ProSiteProfiles,PS50217,Basic-leucine zipper (bZIP) domain profile.,159,222,9.622358,T,05-07-2025,IPR004827,Basic-leucine zipper domain,GO:0003700(InterPro)|GO:0006355(InterPro),-

In [8]:
RNA_IPR_GO_binding = interproscan[
    #(interproscan[11].isin(RBP_IPR_list)) |
    (interproscan[13].astype(str).apply(lambda x: any(go in x for go in RNA_Binding_GO_list)))
]
RNA_IPR_GO_binding

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
139,ENSP00000313199,c2e20191ee2ec384d0d1cf3f6e764227,355,PANTHER,PTHR48033,RNA-BINDING (RRM/RBD/RNP MOTIFS) FAMILY PROTEIN,30,355,9.0E-109,T,05-07-2025,-,-,GO:0000785(PANTHER)|GO:0003723(PANTHER)|GO:000...,-
145,ENSP00000313199,c2e20191ee2ec384d0d1cf3f6e764227,355,ProSiteProfiles,PS50102,Eukaryotic RNA Recognition Motif (RRM) profile.,182,261,17.369957,T,05-07-2025,IPR000504,RNA recognition motif domain,GO:0003723(InterPro),-
154,ENSP00000313199,c2e20191ee2ec384d0d1cf3f6e764227,355,SMART,SM00360,rrm1_1,183,255,9.0E-21,T,05-07-2025,IPR000504,RNA recognition motif domain,GO:0003723(InterPro),-
155,ENSP00000313199,c2e20191ee2ec384d0d1cf3f6e764227,355,SMART,SM00360,rrm1_1,98,170,4.5E-25,T,05-07-2025,IPR000504,RNA recognition motif domain,GO:0003723(InterPro),-
156,ENSP00000313199,c2e20191ee2ec384d0d1cf3f6e764227,355,Pfam,PF00076,RNA recognition motif,100,167,5.0E-14,T,05-07-2025,IPR000504,RNA recognition motif domain,GO:0003723(InterPro),-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387865,ENSP00000300151,c7a486cb818dfc01783287ed1727ad5a,251,PRINTS,PR00060,Ribosomal protein L16 signature,79,91,7.2E-6,T,05-07-2025,IPR000114,"Large ribosomal subunit protein uL16, bacteria...",GO:0003735(InterPro)|GO:0006412(InterPro)|GO:0...,-
387866,ENSP00000300151,c7a486cb818dfc01783287ed1727ad5a,251,PRINTS,PR00060,Ribosomal protein L16 signature,145,174,7.2E-6,T,05-07-2025,IPR000114,"Large ribosomal subunit protein uL16, bacteria...",GO:0003735(InterPro)|GO:0006412(InterPro)|GO:0...,-
387867,ENSP00000300151,c7a486cb818dfc01783287ed1727ad5a,251,PRINTS,PR00060,Ribosomal protein L16 signature,115,144,7.2E-6,T,05-07-2025,IPR000114,"Large ribosomal subunit protein uL16, bacteria...",GO:0003735(InterPro)|GO:0006412(InterPro)|GO:0...,-
387870,ENSP00000300151,c7a486cb818dfc01783287ed1727ad5a,251,PANTHER,PTHR12220,50S/60S RIBOSOMAL PROTEIN L16,2,231,1.5E-83,T,05-07-2025,IPR000114,"Large ribosomal subunit protein uL16, bacteria...",GO:0003735(InterPro)|GO:0003735(PANTHER)|GO:00...,-
387932,ENSP00000358771,59861a7272ce3ecea6f2c668f0e4c98a,523,PANTHER,PTHR12974,PRION-LIKE- Q/N-RICH -DOMAIN-BEARING PROTEIN P...,138,523,9.5E-196,T,05-07-2025,IPR012937,Terminal nucleotidyltransferase,GO:0003723(PANTHER)|GO:0048255(PANTHER)|GO:199...,-

In [9]:
RNA_IPR_GO_binding.drop_duplicates(subset=0)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
139,ENSP00000313199,c2e20191ee2ec384d0d1cf3f6e764227,355,PANTHER,PTHR48033,RNA-BINDING (RRM/RBD/RNP MOTIFS) FAMILY PROTEIN,30,355,9.0E-109,T,05-07-2025,-,-,GO:0000785(PANTHER)|GO:0003723(PANTHER)|GO:000...,-
574,ENSP00000346627,9bc5f9b9e9f91523853431599f59ef04,315,PANTHER,PTHR12461,HYPOXIA-INDUCIBLE FACTOR 1 ALPHA INHIBITOR-REL...,14,267,9.9E-44,T,05-07-2025,-,-,GO:0000049(PANTHER)|GO:0031591(PANTHER),-
607,ENSP00000479069,3ce3e3dd5a485300069f03374459adc8,546,Pfam,PF06881,RNA polymerase II transcription factor SIII (E...,353,449,8.1E-19,T,05-07-2025,IPR010684,"RNA polymerase II transcription factor SIII, s...",GO:0005634(InterPro)|GO:0006368(InterPro)|GO:0...,-
1125,ENSP00000380033,a6a581480ad4413bcd03ede8b630615c,731,ProSiteProfiles,PS51195,DEAD-box RNA helicase Q motif profile.,171,199,10.105238,T,05-07-2025,IPR014014,"RNA helicase, DEAD-box type, Q motif",GO:0003724(InterPro),-
1363,ENSP00000429084,197eb92fd03411500a9682e1499e4d4a,2799,SUPERFAMILY,SSF63570,PABC (PABP) domain,2360,2458,2.22E-23,T,05-07-2025,IPR036053,PABC (PABP) domain,GO:0003723(InterPro),-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385826,ENSP00000428426,79fba4877c3fb533a9a6721a05e40d8f,301,Pfam,PF01096,Transcription factor S-II (TFIIS),261,299,1.6E-15,T,05-07-2025,IPR001222,"Zinc finger, TFIIS-type",GO:0003676(InterPro)|GO:0006351(InterPro)|GO:0...,-
386237,ENSP00000429374,0a6694db2f0ff22ce4dee728f25fcd6e,142,ProSitePatterns,PS00361,Ribosomal protein S10 signature.,43,58,-,T,05-07-2025,IPR018268,"Small ribosomal subunit protein uS10, conserve...",GO:0003723(InterPro)|GO:0003735(InterPro)|GO:0...,-
387332,ENSP00000314348,18d14934595cb019b1c7ba290adee75d,875,ProSiteProfiles,PS51195,DEAD-box RNA helicase Q motif profile.,69,97,9.225721,T,05-07-2025,IPR014014,"RNA helicase, DEAD-box type, Q motif",GO:0003724(InterPro),-
387865,ENSP00000300151,c7a486cb818dfc01783287ed1727ad5a,251,PRINTS,PR00060,Ribosomal protein L16 signature,79,91,7.2E-6,T,05-07-2025,IPR000114,"Large ribosomal subunit protein uL16, bacteria...",GO:0003735(InterPro)|GO:0006412(InterPro)|GO:0...,-
387932,ENSP00000358771,59861a7272ce3ecea6f2c668f0e4c98a,523,PANTHER,PTHR12974,PRION-LIKE- Q/N-RICH -DOMAIN-BEARING PROTEIN P...,138,523,9.5E-196,T,05-07-2025,IPR012937,Terminal nucleotidyltransferase,GO:0003723(PANTHER)|GO:0048255(PANTHER)|GO:199...,-

In [10]:
D_B_ENSP = list(DNA_IPR_GO_binding.drop_duplicates(subset=0)[0])
R_B_ENSP = list(RNA_IPR_GO_binding.drop_duplicates(subset=0)[0])

print(f'DNA binding ENSP : {len(D_B_ENSP)}\nRNA binding ENSP : {len(R_B_ENSP)}')

DNA binding ENSP : 1864
RNA binding ENSP : 1335

In [22]:
DRBP_pred_result = pd.read_csv("/Users/khj/Desktop/Project_ongoing/DRBP/data/DRBP_pred_result/DRBP_pred_concat.csv")
DRBP_pred_result

,ID,sequence,DNA-binding,RNA-binding,DNA-binding probabilities,RNA-binding probabilities
0,>ENSP00000000233,MGLTVSALFSRIFGKKQMRILMVGLDAAGKTTILYKLKLGEIVTTI...,0,0,0.197959,0.000058
1,>ENSP00000000412,MFPFYSCWRTGLLLLLLAVAVRESWQTEEKTCDLVGEKGKESEKEL...,0,0,0.026668,0.000553
2,>ENSP00000000442,MSSQVVGIEPLYIKAEPASPDSPKGSSETETEPPVALAPGPAPTRC...,1,0,0.947597,0.000091
3,>ENSP00000001008,MTAEEMKATESGAQSAPLPMEGVDISPKQDEGVLKVIKREGTGTEM...,0,1,0.469457,0.000029
4,>ENSP00000001146,MLFEGLDLVSALATLAACLVSVTLLLAVSQQLWQLRWAATRDKSCK...,0,0,0.078130,0.020440
...,...,...,...,...,...,...
18216,>ENSP00000498164,MAAPVVAPPGVVVSRANKRSGAGPGGSGGGGARGAEEEPPPPLQAV...,0,0,0.237524,0.010683
18217,>ENSP00000498177,MKFNPFVTSDRSKNRKRHFNAPSHIRRKIMSSPLSKELRQKYNVRS...,0,0,0.721043,0.473582
18218,>ENSP00000498186,MQLRNPELHLGCALALRFLALVSWDIPGARALDNGLARTPTMGWLH...,0,0,0.084342,0.010173
18219,>ENSP00000498190,MSPSLQEGAQLGENKPSTCSFSIERILGLDQKKDCVPLMKPHRPWA...,0,0,0.935315,0.001034
18220,>ENSP00000498205,MANLEESFPRGGTRKIHKPEKAFQQSVEQDNLFDISTEEGSTKRKK...,1,0,0.511566,0.987715

In [23]:
DRBP_pred_result['DNA_domain'] = DRBP_pred_result['ID'].astype(str).apply(
    lambda x: 1 if any(ensp in x for ensp in D_B_ENSP) else 0
)
DRBP_pred_result

,ID,sequence,DNA-binding,RNA-binding,DNA-binding probabilities,RNA-binding probabilities,DNA_domain
0,>ENSP00000000233,MGLTVSALFSRIFGKKQMRILMVGLDAAGKTTILYKLKLGEIVTTI...,0,0,0.197959,0.000058,0
1,>ENSP00000000412,MFPFYSCWRTGLLLLLLAVAVRESWQTEEKTCDLVGEKGKESEKEL...,0,0,0.026668,0.000553,0
2,>ENSP00000000442,MSSQVVGIEPLYIKAEPASPDSPKGSSETETEPPVALAPGPAPTRC...,1,0,0.947597,0.000091,1
3,>ENSP00000001008,MTAEEMKATESGAQSAPLPMEGVDISPKQDEGVLKVIKREGTGTEM...,0,1,0.469457,0.000029,0
4,>ENSP00000001146,MLFEGLDLVSALATLAACLVSVTLLLAVSQQLWQLRWAATRDKSCK...,0,0,0.078130,0.020440,0
...,...,...,...,...,...,...,...
18216,>ENSP00000498164,MAAPVVAPPGVVVSRANKRSGAGPGGSGGGGARGAEEEPPPPLQAV...,0,0,0.237524,0.010683,0
18217,>ENSP00000498177,MKFNPFVTSDRSKNRKRHFNAPSHIRRKIMSSPLSKELRQKYNVRS...,0,0,0.721043,0.473582,0
18218,>ENSP00000498186,MQLRNPELHLGCALALRFLALVSWDIPGARALDNGLARTPTMGWLH...,0,0,0.084342,0.010173,0
18219,>ENSP00000498190,MSPSLQEGAQLGENKPSTCSFSIERILGLDQKKDCVPLMKPHRPWA...,0,0,0.935315,0.001034,1
18220,>ENSP00000498205,MANLEESFPRGGTRKIHKPEKAFQQSVEQDNLFDISTEEGSTKRKK...,1,0,0.511566,0.987715,1

In [24]:
DRBP_pred_result['RNA_domain'] = DRBP_pred_result['ID'].astype(str).apply(
    lambda x: 1 if any(ensp in x for ensp in R_B_ENSP) else 0
)
DRBP_pred_result

,ID,sequence,DNA-binding,RNA-binding,DNA-binding probabilities,RNA-binding probabilities,DNA_domain,RNA_domain
0,>ENSP00000000233,MGLTVSALFSRIFGKKQMRILMVGLDAAGKTTILYKLKLGEIVTTI...,0,0,0.197959,0.000058,0,0
1,>ENSP00000000412,MFPFYSCWRTGLLLLLLAVAVRESWQTEEKTCDLVGEKGKESEKEL...,0,0,0.026668,0.000553,0,0
2,>ENSP00000000442,MSSQVVGIEPLYIKAEPASPDSPKGSSETETEPPVALAPGPAPTRC...,1,0,0.947597,0.000091,1,0
3,>ENSP00000001008,MTAEEMKATESGAQSAPLPMEGVDISPKQDEGVLKVIKREGTGTEM...,0,1,0.469457,0.000029,0,0
4,>ENSP00000001146,MLFEGLDLVSALATLAACLVSVTLLLAVSQQLWQLRWAATRDKSCK...,0,0,0.078130,0.020440,0,0
...,...,...,...,...,...,...,...,...
18216,>ENSP00000498164,MAAPVVAPPGVVVSRANKRSGAGPGGSGGGGARGAEEEPPPPLQAV...,0,0,0.237524,0.010683,0,1
18217,>ENSP00000498177,MKFNPFVTSDRSKNRKRHFNAPSHIRRKIMSSPLSKELRQKYNVRS...,0,0,0.721043,0.473582,0,1
18218,>ENSP00000498186,MQLRNPELHLGCALALRFLALVSWDIPGARALDNGLARTPTMGWLH...,0,0,0.084342,0.010173,0,0
18219,>ENSP00000498190,MSPSLQEGAQLGENKPSTCSFSIERILGLDQKKDCVPLMKPHRPWA...,0,0,0.935315,0.001034,1,0
18220,>ENSP00000498205,MANLEESFPRGGTRKIHKPEKAFQQSVEQDNLFDISTEEGSTKRKK...,1,0,0.511566,0.987715,1,1

In [17]:
DRBP_pred_result.to_csv("/Users/khj/Desktop/Project_ongoing/DRBP/data/DRBP_result_analysis/DRBP_result_with_domain_annotation.csv", index=False)

In [12]:
DNA_IPR_GO_binding_IPR = set(DNA_IPR_GO_binding[11])
DNA_IPR_GO_binding_IPR_df = pd.DataFrame(DNA_IPR_GO_binding_IPR, columns=['Interpro_ID'])
DNA_IPR_GO_binding_IPR_df
#DNA_IPR_GO_binding_IPR_df.to_csv("/Users/khj/Desktop/Project_ongoing/DRBP/data/DRBP_result_analysis/DNA_binding_IPR_final_list.csv", index=False)

    Interpro_ID
0     IPR052856
1     IPR000445
2     IPR042839
3     IPR002205
4     IPR015351
..          ...
719   IPR016743
720   IPR022648
721   IPR007641
722   IPR000770
723   IPR037655

[724 rows x 1 columns]

In [1]:
RNA_IPR_GO_binding_IPR = set(RNA_IPR_GO_binding[11])
RNA_IPR_GO_binding_IPR_df = pd.DataFrame(RNA_IPR_GO_binding_IPR, columns=['Interpro_ID'])
RNA_IPR_GO_binding_IPR_df
#RNA_IPR_GO_binding_IPR_df.to_csv("/Users/khj/Desktop/Project_ongoing/DRBP/data/DRBP_result_analysis/RNA_binding_IPR_final_list.csv", index=False)

NameError: name 'RNA_IPR_GO_binding' is not defined